name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build words
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            file_extension: exe
            file_name: words.exe
            asset_name: words-windows.exe
          - os: ubuntu-latest
            file_name: words
            asset_name: words-ubuntu
  
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install D compiler
      uses: mihails-strasuns/setup-dlang@v0.3.0
      with:
        compiler: ldc-latest

    - name: Write Build Config
      run: 'echo "{ \"name\": \"words\", \"dflags\": \["-of=words-${{ matrix.os }}${{ matrix.file_extension }}\"] }" > dub.json'

    - name: Build Project
      run: 'dub build -y --build=release'

    - name: Cleanup
      run: rm dub.json
  
  release:
    name: Release words
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Get Time
      id: time
      uses: ./.github/actions/get-time

    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ steps.time.outputs.time }}
        release_name: Nightly Build (${{ steps.time.outputs.time }})
        draft: false
        prerelease: true

    - name: Upload Release Asset Windows
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./words-windows-latest.exe
        asset_name: words-windows-latest.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Asset Linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./words-ubuntu-latest
        asset_name: words-ubuntu-latest
        asset_content_type: application/octet-stream
